// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Generic batch of envelopes — the common ingestion format.
 */
export type Envelope = { kind: string, run_id: string, step: bigint, wall_time: number, context: string, payload: { [key in string]?: JsonValue }, };
