// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single histogram data point — bucket counts for a value distribution at one step.
 */
export type HistogramRow = { run_id: string, step: bigint, wall_time: number, key: string, context: string, 
/**
 * Upper bounds for each bucket (length N). First bucket extends from -inf.
 */
bucket_limits: Array<number>, 
/**
 * Per-bucket counts (length N). For cumulative TB data, diff is applied at ingestion.
 */
bucket_counts: Array<bigint>, min: number, max: number, 
/**
 * Total number of values in the distribution.
 */
num: bigint, 
/**
 * Sum of all values.
 */
sum: number, 
/**
 * Sum of squared values (used for std computation).
 */
sum_squares: number, };
