// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single scalar metric data point recorded during training.
 */
export type MetricRow = { run_id: string, step: bigint, wall_time: number, key: string, context: string, value: number, };
