// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filters for listing runs.
 */
export type RunFilter = { project: string | null, state: string | null, sweep_id: string | null, expr: string | null, limit: bigint | null, offset: bigint | null, 
/**
 * None = 不过滤(admin/后台全量);Some(id) = 只看该用户自己拥有的 run。
 */
owner_id: bigint | null, };
