// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Top-level metadata for a tracked run.
 */
export type RunMeta = { run_id: string, project: string, group_name: string | null, name: string | null, state: string, config: JsonValue, env: JsonValue, git_commit: string | null, sweep_id: string | null, created_at: number, heartbeat_at: number | null, tags: Array<string> | null, 
/**
 * 归属用户(本地模式强制 1 = admin;None = 未归属/系统内部)。
 */
owner_id: bigint | null, };
