// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A text sample (LLM generation, prompt/response, transcript).
 */
export type TextRow = { run_id: string, step: bigint, name: string, body: string, };
